sudo: required
dist: trusty

language: python
python: "2.7"

services:
  - docker

before_install:
  - export SPLUNK_HOME="/opt/splunk"
  - export RANDOM_PASSWORD=$(openssl rand -hex 20)
  - wget -q -O - https://www.mongodb.org/static/pgp/server-3.2.pub | sudo apt-key add -
  # Pull docker image
  - docker pull splunk/splunk
  - sudo apt-get update -qq

  # Add DOCKER to iptables, 1/10 times this is needed, force 0 exit status
  - sudo iptables -N DOCKER || true
  - sudo iptables -I INPUT -p tcp --dport $SPLKMGMT -j ACCEPT || true
  - chmod +x ./.travis/*

install:
  # Install Ansible.
  - pip install ansible
  
script:
  - ./.travis/script.sh

#deploy:
#  - provider: script
#  - script: ./.travis/deploy.sh
# - skip_cleanup: true
# - on:
#        branch: master

env:
  - SPLKMGMT=8089
  - ANSIBLE_VERSION=2.3.2.0
