sudo: required

language: generic

services:
  - docker

before_install: 
  - export SPLUNK_HOME="/opt/splunk"
  - export RANDOM_PASSWORD=$(openssl rand -hex 20)
  # Pull docker image
  - docker pull splunk/splunk
  # Add DOCKER to iptables, 1/10 times this is needed, force 0 exit status
  - sudo iptables -N DOCKER || true
  - sudo iptables -I INPUT -p tcp --dport $SPLKMGMT -j ACCEPT || true
  
script:
  - ./.travis/script.sh

deploy:
    provider: script
    script: ./.travis/deploy.sh
    skip_cleanup: true
    on:
        all_branches: true
env:
  - SPLKMGMT=8089
