---
# Playbook to create apps using templates

# - name: Clean bareApps Directory
#   file:
#     state: absent
#     path:  "{{dest_base}}/{{project}}/{{bareApps}}"

# Copy files and directories which are NOT template
- name: Creates Temporary directory
  file: path={{dest_base}}/{{project}}/{{bareApps}} state=directory

# Copy files from template to bareApps in Temporary location
- name: Build necessary non-template files & directories
  synchronize:
    src:  "../files/{{env}}/"
    dest: "{{dest_base}}/{{project}}/{{bareApps}}/"
    delete: yes

# Create Splunk apps directory from template
- name: Ensure App dir Exists
  file:
    path: "{{dest_base}}/{{project}}/{{bareApps}}/{{item | basename | regex_replace('^(?P<appName>.+)__.*$', '\\g<appName>')}}/local"
    state: directory
  with_fileglob:
    - "../templates/common/*.j2"
    - "../templates/shc/*.j2"

# Create Splunk apps from template
- name: Build apps from ready-made templates
  template:
    src={{item}}
    dest={{dest_base}}/{{project}}/{{bareApps}}/{{item | basename | regex_replace('^(?P<appName>.+)__.*$', '\\g<appName>')}}/local/{{item | basename | regex_replace('.*__(?P<confName>.+)\.j2', '\\g<confName>')}}
  with_fileglob:
    - "../templates/common/*.j2"
    - "../templates/shc/*.j2"
