---
# Playbook to copy apps to different Splunk tiers based on a whitelist/blacklist pattern

- name: Clean buildDir
  file:
    state: absent
    path:  "{{dest_base}}/{{project}}/{{buildDir}}"

- name: Create buildDir
  file:
    state: directory
    path:  "{{dest_base}}/{{project}}/{{buildDir}}/{{productTag}}-specific/"

- name: List Apps based on whitelist
  find:
      paths: "{{dest_base}}/{{project}}/{{bareApps}}"
      patterns: "{{item.apps_whitelist.split('|')}}"
      file_type: any
  with_items:
     - "{{es_appMapping}}"
  register: whitelistApps

- name: Copy Apps based on whitelist
  synchronize:
      src: "{{item.1.path}}"
      dest: "{{dest_base}}/{{project}}/{{buildDir}}/{{productTag}}-specific/{{item.0.item.hostname}}/"
      recursive: yes
  with_subelements:
     - "{{whitelistApps.results}}"
     - files

- name: List Apps based on blacklist
  find:
      paths: "{{dest_base}}/{{project}}/{{buildDir}}/{{productTag}}-specific/{{item.hostname}}"
      patterns: "{{item.apps_blacklist.split('|')}}"
      file_type: directory
      recurse: yes
  with_items:
     - "{{es_appMapping}}"
  register: blacklistApps

- name: Delete Apps based on blacklist
  file:
      state: absent
      path: "{{item.1.path}}"
  with_subelements:
     - "{{blacklistApps.results}}"
     - files
