---
- name: Gather Facts of Host
  setup:

- debug:
    msg: "ansible_os_family={{ ansible_os_family }} ansible_distribution={{ ansible_distribution }} ansible_distribution_major_version={{ansible_distribution_major_version}}"

- name: Test to See if selinux is running. DO NOT continue if mode=enforced
  debug:
    msg: "ansible_selinux.mode={{ ansible_selinux.mode }}"
  when: ansible_selinux is defined and ansible_selinux !=False and ansible_selinux.status == 'enabled'
