---

# Common variables for DEV
src_base: ".."
dest_base: "/tmp/jinja"
project: "docker_splunk"
configs: "configs"
buildDir: "buildDir"
bareApps: "bareApps"
composeBaseName: "splunk.docker-compose"
envBaseName: "splunk.env_file"
docker_user: "root"

# sta => standalone
# es => cluster
# inputTag should be either es or sta
inputTag: "es"
env: "dev"

vars_prompt:
  - name: "ansible_sudo_pass"
    prompt: "Sudo password"
    private: yes

# Counters to be reused
# counter: 0

# Docker container specifics
dockerImage: "splunk/splunk"
dockerImageVersion: "latest"
serverList: "{{src_base}}/configs/{{inputTag}}_serverList.csv"
appMapping: "{{src_base}}/configs/{{inputTag}}_appMapping.csv"
