---

# Common variables for DEV
src_base: ".."
dest_base: "/tmp/jinja"
project: "docker_splunk"
configs: "configs"
buildDir: "buildDir"
bareApps: "bareApps"
composeBaseName: "splunk.docker-compose"
envBaseName: "splunk.env_file"

# Ansible Directories
ansible_dir: "{{playbook_dir}}/../../ansible"
config_dir: "{{playbook_dir}}/../../configs"

# sta => standalone
# shc => cluster
# inputTag should be either shc or sta.
# Default is sta, but can be overridden in command line using -e flag
env: "dev"

# vars_prompt:
#   - name: "ansible_sudo_pass"
#     prompt: "Sudo password"
#     private: yes

# Counters to be reused
# counter: 0

# Docker container specifics
dockerImage: "splunk/splunk"
dockerImageVersion: "latest"
serverList: "{{config_dir}}/{{inputTag}}_serverList.csv"
appMapping: "{{config_dir}}/{{inputTag}}_appMapping.csv"
