---

# Common variables for DEV
src_base: ".."
dest_base: "/tmp/jinja"
project: "docker_splunk"
configs: "configs"
buildDir: "buildDir"
bareApps: "bareApps"
composeBaseName: "splunk.docker-compose"
envBaseName: "splunk.env_file"
docker_user: "root"

inputTag: "es"
env: "dev"

vars_prompt:
  - name: "ansible_sudo_pass"
    prompt: "Sudo password"
    private: yes

# Counters to be reused
counter: 0
