---
- name: Build docker compose
  hosts: dev
  gather_facts: no
  vars_files:
    - "{{playbook_dir}}/../group_vars/all.yml"
    - "{{playbook_dir}}/../group_vars/apps_vars.yml"
    - "{{playbook_dir}}/../group_vars/{{inputTag}}.yml"
  roles:
    - "{{playbook_dir}}/../roles/prereqs"
    - "{{playbook_dir}}/../roles/copy_splunk_apps"
    - "{{playbook_dir}}/../roles/build_splunk_compose"


