---
- name: Clearup running docker containers
  hosts: dev
  gather_facts: no
  vars_files:
    - "{{playbook_dir}}/../group_vars/all.yml"
    - "{{playbook_dir}}/../group_vars/apps_vars.yml"
    - "{{playbook_dir}}/../group_vars/sta.yml"
  roles:
    - "{{playbook_dir}}/../roles/prereqs"
    # - "{{playbook_dir}}/../roles/build_splunk_compose"
    - "{{playbook_dir}}/../roles/docker_splunk_actions/cleanup"
