---
# This playbook is to trigger compose files

- name: Project to automate Splunk (Standlone & Cluster) with Ansible
  hosts: dev
  gather_facts: no
  vars_files:
    - group_vars/all.yml
    - group_vars/apps_vars.yml
    # - group_vars/compute_vars.yml
  roles:
    - mkouhei.include_csv
    - build_splunk_apps
    - copy_splunk_apps
    - build_splunk_compose
    - docker_splunk_actions
