---
# Playbook to clean/Kill docker containers

- name: Identify docker-compose path
  find:
      paths: "{{dest_base}}/{{project}}"
      patterns: "{{inputTag}}*.yml"
      file_type: file
  register: docker_compose_files

# - name: Print available docker-compose files
#   debug:
#     msg: "docker-compose File={{ item }}"
#   with_items:
#     - "{{docker_compose_files.files}}"

- name: Kill docker running containers
  shell: docker-compose -f "{{item.path}}" kill
  with_items:
    - "{{docker_compose_files.files}}"
  ignore_errors: true

- name: Remove docker volumes
  shell: docker-compose -f "{{item.path}}" rm -v -f
  with_items:
    - "{{docker_compose_files.files}}"
  ignore_errors: true

