---
# Playbook to start & deploy docker containers
# Run with sudo permissions

- name: Identify docker-compose path
  find:
      paths: "{{dest_base}}/{{project}}"
      patterns: "*.yml"
      file_type: file
  register: docker_compose_files

- name: Deploy docker containers
  shell: docker-compose -f "{{item.path}}" up -d
  with_items:
    - "{{docker_compose_files.files}}"
  become: yes
  become_user: "{{docker_user}}"

# Bootstrap a dynamic captain once all is done
- name: Bootstrap Search Head Cluster
  shell: docker exec -d shc_member_02  /opt/splunk/bin/splunk bootstrap shcluster-captain -servers_list "{{distributedSearch_uri}}"
  become: yes
  become_user: "{{docker_user}}"
